export const CATEGORIES_LOAD = 'CATEGORIES_LOAD';
export const CATEGORIES_FULLFILLED = 'CATEGORIES_FULLFILLED';
export const CATEGORIES_ERROR = 'CATEGOREIS_ERROR';

export const POST_LOAD = 'POST_LOAD';
export const POST_FULLFILLED = 'POST_FULLFILLED';
export const POST_ERROR = 'POST_ERROR';
export const VOTE_FULLFILLED = 'VOTE_FULLFILLED';